import { TeslaModel } from "./types";

export const TESLA_MODELS: TeslaModel[] = [
  {
    id: "model-3-standard",
    name: "Model 3",
    range: 272,
    efficiency: 255,
    batteryCapacity: 60,
    maxChargeRate: 170,
  },
  {
    id: "model-3-long-range",
    name: "Model 3 Long Range",
    range: 358,
    efficiency: 240,
    batteryCapacity: 82,
    maxChargeRate: 250,
  },
  {
    id: "model-3-performance",
    name: "Model 3 Performance",
    range: 315,
    efficiency: 260,
    batteryCapacity: 82,
    maxChargeRate: 250,
  },
  {
    id: "model-y-standard",
    name: "Model Y",
    range: 283,
    efficiency: 270,
    batteryCapacity: 60,
    maxChargeRate: 170,
  },
  {
    id: "model-y-long-range",
    name: "Model Y Long Range",
    range: 330,
    efficiency: 255,
    batteryCapacity: 82,
    maxChargeRate: 250,
  },
  {
    id: "model-y-performance",
    name: "Model Y Performance",
    range: 303,
    efficiency: 275,
    batteryCapacity: 82,
    maxChargeRate: 250,
  },
  {
    id: "model-s-long-range",
    name: "Model S",
    range: 405,
    efficiency: 245,
    batteryCapacity: 100,
    maxChargeRate: 250,
  },
  {
    id: "model-s-plaid",
    name: "Model S Plaid",
    range: 396,
    efficiency: 253,
    batteryCapacity: 100,
    maxChargeRate: 250,
  },
  {
    id: "model-x-long-range",
    name: "Model X",
    range: 348,
    efficiency: 290,
    batteryCapacity: 100,
    maxChargeRate: 250,
  },
  {
    id: "model-x-plaid",
    name: "Model X Plaid",
    range: 326,
    efficiency: 310,
    batteryCapacity: 100,
    maxChargeRate: 250,
  },
  {
    id: "cybertruck-awd",
    name: "Cybertruck AWD",
    range: 318,
    efficiency: 340,
    batteryCapacity: 123,
    maxChargeRate: 250,
  },
  {
    id: "cybertruck-beast",
    name: "Cybertruck Cyberbeast",
    range: 301,
    efficiency: 370,
    batteryCapacity: 123,
    maxChargeRate: 250,
  },
];
